---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=1002
      - PGID=1003
      - TZ=Asia/Seoul
      - VERSION=docker
      - PLEX_MEDIA_SERVER_USER=plex
    volumes:
      - ./config:/config
      - /mnt/gdrive/video:/video
      - /tmp/plex:/tmp
      - /tmp/plextranscode:/transcode
    restart: unless-stopped
